## **Some other points of functions**

- **lets use an example of specific gravity**

In [1]:
def api(sg):
    '''"api function will take input as specific gravity and 
    return density in API"'''
    
    api = 141.5/sg -131.5
    print(f'the api gravity is {api}')

In [2]:
api(0.5)

the api gravity is 151.5


- **comes to Darcy Equation**

In [3]:
def darcy_calculation(C = 141.2):
    '''Gives value of Darcy coefficient
    Inputs: Flowrate,viscosity,formation Volume factor, Permeabilty,Net Pay Thickness
    Output: darcy Coefficient'''
    q = float(input('Enter the Flowrate in STB/d\D: '))
    mu = float(input('Enter Viscosity in cP: '))
    B = float(input('Enter FVF rb/STB '))
    k = float(input('Enter Perm mD '))
    h = float(input('Enter Res Thickness ft:  '))
    
    darcy_calculation = C*q*mu*B/(k*h)
    return darcy_calculation
    

In [7]:
Cofficient = darcy_calculation()

Enter the Flowrate in STB/d\D: 1
Enter Viscosity in cP: 2
Enter FVF rb/STB 3
Enter Perm mD 10
Enter Res Thickness ft:  300


In [11]:
Cofficient

0.2824

---
---

## NumPy

**Array**

>**basically used to store the data**

>**much faster than other languages**

First you need to import the numpy

In [19]:
import numpy as np

In [20]:
np.array(55565)

array(55565)

In [22]:
#Example lets store the porosity data

porosity = [0, 2, 3, 5, 6, 9]

In [23]:
porosity

[0, 2, 3, 5, 6, 9]

In [24]:
type(porosity)

list

change it into array

In [25]:
arr_porosity = np.array(porosity)

In [26]:
arr_porosity

array([0, 2, 3, 5, 6, 9])

In [27]:
type(arr_porosity)

numpy.ndarray

Also you can change it into tuple

In [28]:
tup_poro = tuple(porosity)

In [29]:
tup_poro

(0, 2, 3, 5, 6, 9)

In [30]:
type(tup_poro)

tuple

---
---

# Dimensions



> **1. Zero Dimension**

In [31]:
arr = np.array(45)

In [32]:
arr

array(45)

for checking the dimension of "array" use "ndim"

In [33]:
arr.ndim

0

---

> **2. One Dimension**

In [49]:
# for one dimension you have to use two brackets
arr_1d = np.array([1,2,3,6,5,4,9])

In [40]:
arr_1d

array([1, 2, 3, 6, 5, 4, 9])

In [41]:
arr_1d.ndim

1

---

> **3. Two Dimension**

In [115]:
# for two dimension you have to use three brackets
arr_2d = np.array([[1,2,3],[2,3,6],[4,5,6]])

In [116]:
arr_2d

array([[1, 2, 3],
       [2, 3, 6],
       [4, 5, 6]])

In [117]:
arr_2d.ndim

2

In [54]:
#what if number of elements in 1D arrays are different:
arra_1d = np.array([[1,2,3],[2,3,6],[4,5,6,5]])

C:\Users\user\AppData\Local\Temp\ipykernel_10348\1797122181.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arra_1d = np.array([[1,2,3],[2,3,6],[4,5,6,5]])


In [55]:
arra_1d

array([list([1, 2, 3]), list([2, 3, 6]), list([4, 5, 6, 5])], dtype=object)

In [57]:
'it will show 1 dimension as the no. of elements are different, array is not taking it as a dimension, it take it as a list'
arra_1d.ndim

1

- **In NumPy array you can store no. , floats, strings**

In [58]:
a = np.array ([2,2.3,'abcd'])

In [59]:
a

array(['2', '2.3', 'abcd'], dtype='<U32')

---

> **4. Three Dimention**

In [73]:
arr_3d = np.array([[[1,2,3,6],[3,4,5,7],[4,5,9,4]],[[1,2,1,3],[3,4,4,5],[4,8,7,8]]])

In [74]:
arr_3d

array([[[1, 2, 3, 6],
        [3, 4, 5, 7],
        [4, 5, 9, 4]],

       [[1, 2, 1, 3],
        [3, 4, 4, 5],
        [4, 8, 7, 8]]])

In [75]:
arr_3d.ndim

3

In [83]:
#also we can do some indices
arr_3d[1][0][1]

2

In [86]:
#Example : find pick out the no "9998" 
arra_4d = np.array([[[[1,2,3,4],[3,4,5,6],[4,5,6,4]],[[31,26,64,65],[56,59,56,12],[45,48,49,66]]],
                    [[[11,22,33,66],[78,89,56,15],[45,89,69,326]],[[54,545,54,9998],[78,15,91,61],[45,45,65,31]]]])

In [87]:
arra_4d

array([[[[   1,    2,    3,    4],
         [   3,    4,    5,    6],
         [   4,    5,    6,    4]],

        [[  31,   26,   64,   65],
         [  56,   59,   56,   12],
         [  45,   48,   49,   66]]],


       [[[  11,   22,   33,   66],
         [  78,   89,   56,   15],
         [  45,   89,   69,  326]],

        [[  54,  545,   54, 9998],
         [  78,   15,   91,   61],
         [  45,   45,   65,   31]]]])

In [96]:
arra_4d[1][1][0][3]

9998

- **dont confuse with the no. of bracket**

Zero dimension - []

first dimesion - [[]]

three dimension - [[[]]]

four dimension - [[[[]]]]

**ndin = gives you the no. of dimension**

**ndmin = add the no. of dimensions**

In [101]:
#you can practice by doing this
 
    check_arr = np.array([3,2,6],ndmin = 4)

In [102]:
check_arr

array([[[[3, 2, 6]]]])

---

## Shape: Checking the shape of array

> 1 diemsion

In [112]:
arr_1d

array([list([1, 2, 3]), list([2, 3, 6]), list([4, 5, 6, 5])], dtype=object)

In [126]:
arr_1d.shape

(3,)

> 2 dimension

In [118]:
arr_2d

array([[1, 2, 3],
       [2, 3, 6],
       [4, 5, 6]])

In [119]:
arr_2d.shape

(3, 3)

> 3 dimension

In [120]:
arr_3d

array([[[1, 2, 3, 6],
        [3, 4, 5, 7],
        [4, 5, 9, 4]],

       [[1, 2, 1, 3],
        [3, 4, 4, 5],
        [4, 8, 7, 8]]])

In [122]:
arr_3d.shape

(2, 3, 4)

> 4 dimension

In [124]:
arra_4d

array([[[[   1,    2,    3,    4],
         [   3,    4,    5,    6],
         [   4,    5,    6,    4]],

        [[  31,   26,   64,   65],
         [  56,   59,   56,   12],
         [  45,   48,   49,   66]]],


       [[[  11,   22,   33,   66],
         [  78,   89,   56,   15],
         [  45,   89,   69,  326]],

        [[  54,  545,   54, 9998],
         [  78,   15,   91,   61],
         [  45,   45,   65,   31]]]])

In [125]:
arra_4d.shape

(2, 2, 3, 4)

Other Example

In [131]:
arr_7 = np.array([3,2,6],ndmin = 5)

In [132]:
arr_7

array([[[[[3, 2, 6]]]]])

In [133]:
arr_7.shape

(1, 1, 1, 1, 3)

---

# Generating Arrays

**arange**

- np arange (start, stop, step)

In [134]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

Q. makes an array of pressures ranging from 0 to 5000 psi with a step size of 500 psiu

- np.arange(0,5000,500)
- np.arange(0,5001,500)
- np.arange(0,5500,500)

In [138]:
pressure_01 = np.arange(0,5000,500)

In [139]:
pressure_01

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500])

In [140]:
pressure_02 = np.arange(0,5001,500)

In [141]:
pressure_02

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000])

In [142]:
pressure_03 = np.arange(0,5500,500)

In [143]:
pressure_03

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000])

---

# Linspace: create linearly spaced arrays