 ## Reshape of array

In [2]:
import numpy as np

In [3]:
perm = np.array([[[[1,2,3,4],[3,4,5,6],[4,5,6,4]],[[31,26,64,65],[56,59,56,12],[45,48,49,66]]],
                    [[[11,22,33,66],[78,89,56,15],[45,89,69,326]],[[54,545,54,9998],[78,15,91,61],[45,45,65,31]]]])

In [4]:
perm

array([[[[   1,    2,    3,    4],
         [   3,    4,    5,    6],
         [   4,    5,    6,    4]],

        [[  31,   26,   64,   65],
         [  56,   59,   56,   12],
         [  45,   48,   49,   66]]],


       [[[  11,   22,   33,   66],
         [  78,   89,   56,   15],
         [  45,   89,   69,  326]],

        [[  54,  545,   54, 9998],
         [  78,   15,   91,   61],
         [  45,   45,   65,   31]]]])

In [5]:
perm.shape

(2, 2, 3, 4)

 > **reshape of array will be the multiple of no.of elements**

In [6]:
#Example
perm_0 = np.array([1,2,3,6,5,4,7,8,9,6,4,1,63,6,4,5,6,1,3,6,4,9,4,6,1,96,4,1,63,4,4,9,1,3,16])

In [7]:
perm_0.shape

(35,)

In [8]:
perm_0.reshape(7,5)

array([[ 1,  2,  3,  6,  5],
       [ 4,  7,  8,  9,  6],
       [ 4,  1, 63,  6,  4],
       [ 5,  6,  1,  3,  6],
       [ 4,  9,  4,  6,  1],
       [96,  4,  1, 63,  4],
       [ 4,  9,  1,  3, 16]])

In [9]:
perm_0

array([ 1,  2,  3,  6,  5,  4,  7,  8,  9,  6,  4,  1, 63,  6,  4,  5,  6,
        1,  3,  6,  4,  9,  4,  6,  1, 96,  4,  1, 63,  4,  4,  9,  1,  3,
       16])

In [10]:
perm_0.reshape(5,7)

array([[ 1,  2,  3,  6,  5,  4,  7],
       [ 8,  9,  6,  4,  1, 63,  6],
       [ 4,  5,  6,  1,  3,  6,  4],
       [ 9,  4,  6,  1, 96,  4,  1],
       [63,  4,  4,  9,  1,  3, 16]])

---

In [11]:
#Example

perm_01 = np.array([1,2,3,6,5,4,7,8,9,6,4,1,63,6,4,5,6,1,3,6,4,9,4,6,1,96,4,1,63,4,4,9,1,3,16,5,6,9,2,1])

In [12]:
perm_01

array([ 1,  2,  3,  6,  5,  4,  7,  8,  9,  6,  4,  1, 63,  6,  4,  5,  6,
        1,  3,  6,  4,  9,  4,  6,  1, 96,  4,  1, 63,  4,  4,  9,  1,  3,
       16,  5,  6,  9,  2,  1])

In [13]:
perm_01.shape

(40,)

In [14]:
perm_01.reshape(4,10)

array([[ 1,  2,  3,  6,  5,  4,  7,  8,  9,  6],
       [ 4,  1, 63,  6,  4,  5,  6,  1,  3,  6],
       [ 4,  9,  4,  6,  1, 96,  4,  1, 63,  4],
       [ 4,  9,  1,  3, 16,  5,  6,  9,  2,  1]])

we can change shape into another dimension

In [15]:
perm_01.reshape(8,5)

array([[ 1,  2,  3,  6,  5],
       [ 4,  7,  8,  9,  6],
       [ 4,  1, 63,  6,  4],
       [ 5,  6,  1,  3,  6],
       [ 4,  9,  4,  6,  1],
       [96,  4,  1, 63,  4],
       [ 4,  9,  1,  3, 16],
       [ 5,  6,  9,  2,  1]])

In [16]:
perm_01.reshape(2,2,10)

array([[[ 1,  2,  3,  6,  5,  4,  7,  8,  9,  6],
        [ 4,  1, 63,  6,  4,  5,  6,  1,  3,  6]],

       [[ 4,  9,  4,  6,  1, 96,  4,  1, 63,  4],
        [ 4,  9,  1,  3, 16,  5,  6,  9,  2,  1]]])

In [17]:
perm_01.reshape(2,2,2,5)

array([[[[ 1,  2,  3,  6,  5],
         [ 4,  7,  8,  9,  6]],

        [[ 4,  1, 63,  6,  4],
         [ 5,  6,  1,  3,  6]]],


       [[[ 4,  9,  4,  6,  1],
         [96,  4,  1, 63,  4]],

        [[ 4,  9,  1,  3, 16],
         [ 5,  6,  9,  2,  1]]]])

also check the dimension

In [18]:
perm_01.reshape(2,2,2,5).ndim

4

---

Q . poro = np.array([4,1,1,5,6,8,44,6,4,1,6,8,4,6,1,6,5,2,6,4,41,6,5,69,61,4,4,641,6,44,6,3,6,4,6,41,4,6,1,46,47,16,4,94,1,4])

change its dimension into
- 2d
- 3d
- 4d
- 5d

In [19]:
poro = np.array([4,1,1,5,6,8,44,6,4,1,6,8,4,6,1,6,5,2,6,4,41,6,5,69,61,4,4,641,6,44,6,3,6,4,6,41])

In [20]:
poro.shape

(36,)

In [21]:
poro_2d = poro.reshape(6,6)
poro_3d = poro.reshape(2,3,6)
poro_4d = poro.reshape(2,3,2,3)
poro_5d = poro.reshape(1,2,3,2,3)

In [22]:
poro_2d

array([[  4,   1,   1,   5,   6,   8],
       [ 44,   6,   4,   1,   6,   8],
       [  4,   6,   1,   6,   5,   2],
       [  6,   4,  41,   6,   5,  69],
       [ 61,   4,   4, 641,   6,  44],
       [  6,   3,   6,   4,   6,  41]])

In [23]:
poro_3d

array([[[  4,   1,   1,   5,   6,   8],
        [ 44,   6,   4,   1,   6,   8],
        [  4,   6,   1,   6,   5,   2]],

       [[  6,   4,  41,   6,   5,  69],
        [ 61,   4,   4, 641,   6,  44],
        [  6,   3,   6,   4,   6,  41]]])

In [24]:
poro_4d

array([[[[  4,   1,   1],
         [  5,   6,   8]],

        [[ 44,   6,   4],
         [  1,   6,   8]],

        [[  4,   6,   1],
         [  6,   5,   2]]],


       [[[  6,   4,  41],
         [  6,   5,  69]],

        [[ 61,   4,   4],
         [641,   6,  44]],

        [[  6,   3,   6],
         [  4,   6,  41]]]])

---

> **if we know only one dimension and dont know the another one, use (- 1) to get the result**



In [25]:
perm_01

array([ 1,  2,  3,  6,  5,  4,  7,  8,  9,  6,  4,  1, 63,  6,  4,  5,  6,
        1,  3,  6,  4,  9,  4,  6,  1, 96,  4,  1, 63,  4,  4,  9,  1,  3,
       16,  5,  6,  9,  2,  1])

In [26]:
perm_01.shape

(40,)

In [27]:
perm_01.reshape(5, -1)

array([[ 1,  2,  3,  6,  5,  4,  7,  8],
       [ 9,  6,  4,  1, 63,  6,  4,  5],
       [ 6,  1,  3,  6,  4,  9,  4,  6],
       [ 1, 96,  4,  1, 63,  4,  4,  9],
       [ 1,  3, 16,  5,  6,  9,  2,  1]])

In [28]:
perm_01.reshape(-1, 2, 5)

array([[[ 1,  2,  3,  6,  5],
        [ 4,  7,  8,  9,  6]],

       [[ 4,  1, 63,  6,  4],
        [ 5,  6,  1,  3,  6]],

       [[ 4,  9,  4,  6,  1],
        [96,  4,  1, 63,  4]],

       [[ 4,  9,  1,  3, 16],
        [ 5,  6,  9,  2,  1]]])

Also you can check the shape

In [29]:
perm_01.reshape(-1, 2, 5).shape

(4, 2, 5)

In [30]:
perm_01.reshape( -1, 2, 2, 5)

array([[[[ 1,  2,  3,  6,  5],
         [ 4,  7,  8,  9,  6]],

        [[ 4,  1, 63,  6,  4],
         [ 5,  6,  1,  3,  6]]],


       [[[ 4,  9,  4,  6,  1],
         [96,  4,  1, 63,  4]],

        [[ 4,  9,  1,  3, 16],
         [ 5,  6,  9,  2,  1]]]])

In [31]:
perm_01.reshape( -1, 2, 2, 5).shape

(2, 2, 2, 5)

## Slicing in array

In [60]:
perm = np.array([[4,1,1,5,6],[8,44,6,4,1],[6,8,4,6,1],[6,5,2,6,4]])

In [74]:
perm

array([[ 4,  1,  1,  5,  6],
       [ 8, 44,  6,  4,  1],
       [ 6,  8,  4,  6,  1],
       [ 6,  5,  2,  6,  4]])

- **Column Slicing :  perm [x axis, y axis]**

In [102]:

perm[1:3, 2:4]

array([[6, 4],
       [4, 6]])

In [71]:
# [-1] it will counts from below

perm[-3:]

array([[ 8, 44,  6,  4,  1],
       [ 6,  8,  4,  6,  1],
       [ 6,  5,  2,  6,  4]])

Reverse it

In [75]:
perm[-3: ,-1: :-1]

array([[ 1,  4,  6, 44,  8],
       [ 1,  6,  4,  8,  6],
       [ 4,  6,  2,  5,  6]])

In [78]:
# if i need an element 4
perm[-3: ,-1: :-1][1,2]

4

---

In [79]:
#Example: Slice out array([[ 56,  15],
#                         [ 69, 326]]) .

perm_03 = np.array([[[[1,2,3,4],[3,4,5,6],[4,5,6,4]],[[31,26,64,65],[56,59,56,12],[45,48,49,66]]],
                    [[[11,22,33,66],[78,89,56,15],[45,89,69,326]],[[54,545,54,9998],[78,15,91,61],[45,45,65,31]]]])

In [80]:
#Step 1:

perm_03

array([[[[   1,    2,    3,    4],
         [   3,    4,    5,    6],
         [   4,    5,    6,    4]],

        [[  31,   26,   64,   65],
         [  56,   59,   56,   12],
         [  45,   48,   49,   66]]],


       [[[  11,   22,   33,   66],
         [  78,   89,   56,   15],
         [  45,   89,   69,  326]],

        [[  54,  545,   54, 9998],
         [  78,   15,   91,   61],
         [  45,   45,   65,   31]]]])

In [93]:
#Step 2:

perm_03[1][0]

array([[ 11,  22,  33,  66],
       [ 78,  89,  56,  15],
       [ 45,  89,  69, 326]])

In [99]:
#Step 3:

perm_03[1][0][1:3]

array([[ 78,  89,  56,  15],
       [ 45,  89,  69, 326]])

In [107]:
#Step 4

perm_03[1][0][1:3][0:2, 2:4]

array([[ 56,  15],
       [ 69, 326]])

----

In [109]:
#Example: Slice out array  array([[  54, 9998],  Also reverse it.
#                               [  91,   61]]).

perm_04 = np.array([[[[1,2,3,4],[3,4,5,6],[4,5,6,4]],[[31,26,64,65],[56,59,56,12],[45,48,49,66]]],
                    [[[11,22,33,66],[78,89,56,15],[45,89,69,326]],[[54,545,54,9998],[78,15,91,61],[45,45,65,31]]]])

In [110]:
#Step 1
perm_04

array([[[[   1,    2,    3,    4],
         [   3,    4,    5,    6],
         [   4,    5,    6,    4]],

        [[  31,   26,   64,   65],
         [  56,   59,   56,   12],
         [  45,   48,   49,   66]]],


       [[[  11,   22,   33,   66],
         [  78,   89,   56,   15],
         [  45,   89,   69,  326]],

        [[  54,  545,   54, 9998],
         [  78,   15,   91,   61],
         [  45,   45,   65,   31]]]])

In [112]:
#Step 2
perm_04[1][1]

array([[  54,  545,   54, 9998],
       [  78,   15,   91,   61],
       [  45,   45,   65,   31]])

In [114]:
#Step 3
perm_04[1][1][0:2]

array([[  54,  545,   54, 9998],
       [  78,   15,   91,   61]])

In [120]:
#Step 4
perm_04[1][1][0:2][0:3, 2:4]

array([[  54, 9998],
       [  91,   61]])

In [121]:
#Step 5: Reverse it
perm_04[1][1][0:2][0:3, 2:4][-1: :-1]

array([[  91,   61],
       [  54, 9998]])

---

## Random Number Generation

**1. Randint : it is used to get random decimal integers results**

> **Syntex: np.random.randint(min,max,shape)**

In [146]:
perm_05 = np.random.randint(50,55,(5,5))

In [143]:
perm_05

array([[54, 54, 50, 51, 50],
       [54, 50, 53, 54, 50],
       [50, 52, 51, 53, 51],
       [53, 50, 52, 50, 51],
       [51, 51, 51, 51, 54]])

- **each time we run the same code, we will get different random results**

In [147]:
perm_05

array([[51, 54, 52, 52, 54],
       [54, 50, 53, 50, 51],
       [50, 51, 54, 51, 53],
       [50, 51, 50, 52, 50],
       [51, 54, 52, 52, 52]])

- **to stop getting random results we have use:   np.random.seed()**

In [151]:
np.random.seed(5)

perm_05 = np.random.randint(50,55,(5,5))

In [153]:
perm_05

array([[53, 50, 51, 50, 54],
       [53, 50, 50, 54, 51],
       [50, 53, 54, 53, 51],
       [54, 52, 51, 51, 52],
       [51, 51, 51, 52, 50]])

---

**2. Rand : here we dont have to mension any max and min number...all random number will be generated by itself**

> **Syntex :  np.random.rand(shape)**

In [158]:
np.random.seed(2)

saturation = np.random.rand(4,5)

In [159]:
saturation

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987],
       [0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548]])

also you can change the shape of it

In [165]:
np.random.seed(2)

saturation_01 = np.random.rand(3,4,5)

In [167]:
saturation_01

array([[[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
        [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
        [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987],
        [0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548]],

       [[0.50524609, 0.0652865 , 0.42812233, 0.09653092, 0.12715997],
        [0.59674531, 0.226012  , 0.10694568, 0.22030621, 0.34982629],
        [0.46778748, 0.20174323, 0.64040673, 0.48306984, 0.50523672],
        [0.38689265, 0.79363745, 0.58000418, 0.1622986 , 0.70075235]],

       [[0.96455108, 0.50000836, 0.88952006, 0.34161365, 0.56714413],
        [0.42754596, 0.43674726, 0.77655918, 0.53560417, 0.95374223],
        [0.54420816, 0.08209492, 0.3663424 , 0.8508505 , 0.40627504],
        [0.02720237, 0.24717724, 0.06714437, 0.99385201, 0.97058031]]])

---

In [168]:
#Example: generate values b/w 50 to 100 containg float, decimal numbers, shape = (4,5).

In [178]:
numbers = np.random.randint(50,100,(4,5))
decimal = np.random.rand(4,5)

In [177]:
numbers

array([[71, 92, 99, 69, 78],
       [83, 58, 93, 72, 74],
       [97, 61, 51, 93, 55],
       [57, 66, 91, 78, 65]])

In [180]:
decimal

array([[4.63742607e-01, 8.52288956e-01, 2.12767370e-01, 1.23587469e-04,
        9.28962625e-02],
       [1.75116384e-01, 5.14859163e-01, 8.79990349e-01, 7.84791918e-01,
        5.29821174e-01],
       [2.73837868e-01, 2.63841491e-02, 8.69708626e-01, 2.75437869e-01,
        1.45210356e-01],
       [5.05411634e-01, 3.35094665e-01, 1.61695429e-01, 2.19289972e-01,
        8.36517649e-01]])

but i need values b/w 50 to 100

In [183]:
numbers+decimal

array([[67.46374261, 87.85228896, 81.21276737, 84.00012359, 66.09289626],
       [92.17511638, 98.51485916, 86.87999035, 72.78479192, 69.52982117],
       [81.27383787, 67.02638415, 95.86970863, 58.27543787, 87.14521036],
       [59.50541163, 71.33509467, 86.16169543, 89.21928997, 90.83651765]])

---

**3. Choice : random values from the provided values**

In [186]:
# Each time you run the code, output change, it takes the values from provided values

np.random.choice([5,9,4,94,94,94,4,1,58,96,4,9,4])

94

In [188]:
#you also put some parameters

np.random.choice([5,9,4,94,94,94,4,1,58,96,4,9,4], size = (8,9))

array([[96, 94, 96, 58, 94, 94,  4,  4,  4],
       [ 4,  4,  9, 94,  1, 94,  9, 94,  4],
       [ 1, 94, 94,  9,  4,  4,  9, 94,  4],
       [ 4,  4,  4,  9,  4,  9, 96,  4,  5],
       [94,  4, 94, 94,  4,  4, 58,  9, 96],
       [ 4,  1,  9,  4, 94,  4,  5, 94,  4],
       [ 4,  4,  1, 96, 94,  9,  9, 96, 96],
       [ 9,  5, 58,  5,  4, 58, 94, 94, 94]])